name: Terraform CI

on:
  push:
    paths:
      - 'infra/**'
      - 'lambda/**'
  pull_request:
    paths:
      - 'infra/**'
      - 'lambda/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (for Lambda packaging)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform fmt
        run: terraform -chdir=infra fmt -check

      - name: Terraform init
        run: terraform -chdir=infra init -input=false

      - name: Terraform validate
        run: terraform -chdir=infra validate

      - name: Terraform plan (dry-run)
        run: terraform -chdir=infra plan -no-color

      - name: Package Lambda
        run: |
          cd lambda/zipper
          pip install -r requirements.txt -t .
          zip -r ../../infra/zipper.zip .
